version: '3.8'

services:
  http-server:
    build: .
    ports:
      - "8080:8080"
    container_name: http-server-compose
    volumes:
      - ./logs:/app/logs
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

